---
- include: galera_lb_haproxy_configs.yml
  when:
    - galera_lb_type == 'haproxy'

- include: galera_lb_haproxy_services.yml
  when:
    - galera_lb_type == 'haproxy'

- include: galera_lb_maxscale_configs.yml
  when:
    - galera_lb_type == 'maxscale'

- include: galera_lb_maxscale_services.yml
  when:
    - galera_lb_type == 'maxscale'
