---
- name: Remove Configurations Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql/conf.d
    - /etc/mysql

- name: Remove Galera Run Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/run/mysqld

- name: Remove Galera Databases Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql
    - /var/lib/mysql/bin
    - /var/lib/mysql/data
    - /var/lib/mysql/log
    - /var/lib/mysql/tmp
