---
- name: Remove Configurations Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql

- name: Remove Galera Run Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/run/mysqld

- name: Remove Galera Logs Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/mysql

- name: Remove Galera Databases Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql
