---
- name: Get HAProxy Service Info
  shell: service haproxy status | grep not-found || true
  args:
    warn: false
  register: haproxy_service_info
  when:
    - service_init_status.stat.exists

- name: Disable HAProxy Node Service
  service:
    name: haproxy
    enabled: no
    state: stopped
  when:
    - haproxy_service_info.stdout.find("not-found") == -1

- name: Wait for 5 Seconds Before Killing All HAProxy Service
  wait_for:
    timeout: 5

- name: Kill All Remaining HAProxy Service
  shell: killall haproxy || true
  args:
    warn: false

- name: Wait for 5 Seconds After Killing All HAProxy Service
  wait_for:
    timeout: 5

- name: Reload HAProxy Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk
