---
- include: facts.yml

- include: haproxy_services.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'haproxy'

- include: haproxy_cleanups.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'haproxy'

- include: haproxy_packages.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'haproxy'
    - full_uninstall

- include: maxscale_services.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'maxscale'

- include: maxscale_cleanups.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'maxscale'

- include: maxscale_packages.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'maxscale'
    - full_uninstall

- include: galera_services.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_cleanups.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: zfs_mounts.yml
  when:
    - inventory_hostname in groups['galera_node']
    - zfs_backend
    - full_uninstall

- include: galera_directories.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_packages.yml
  when:
    - inventory_hostname in groups['galera_node']
    - full_uninstall

- include: galera_users.yml
  when:
    - inventory_hostname in groups['galera_node']
    - full_uninstall

- include: xinetd_services.yml
  when:
    - inventory_hostname in groups['galera_node']
    - full_uninstall

- include: zfs_blocks.yml
  when:
    - inventory_hostname in groups['galera_node']
    - zfs_backend
    - full_uninstall

- include: os_cleanups.yml
