---
- name: Uninstall MaxScale Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    purge: yes
    state: absent
  with_items:
    - maxscale

- name: Uninstall MaxScale Repository
  file:
    path: "/etc/apt/sources.list.d/maxscale.list"
    state: absent

- name: Uninstall MaxScale Keyring
  apt_key:
    id: "{{ item }}"
    state: absent
  with_items:
    - "0x8167EE24"
    - "0xE3C94F49"
    - "0xcbcb082a1bb943db"
    - "0xF1656F24C74CD1D8"
    - "0x135659e928c12247"
