---
- name: Get MaxScale Service Info
  shell: service maxscale status | grep not-found || true
  args:
    warn: false
  register: maxscale_service_info
  when:
    - service_init_status.stat.exists

- name: Disable MaxScale Node Service
  service:
    name: maxscale
    enabled: no
    state: stopped
  when:
    - maxscale_service_info.stdout.find("not-found") == -1

- name: Wait for 5 Seconds Before Killing All MaxScale Service
  wait_for:
    timeout: 5

- name: Kill All Remaining MaxScale Service
  shell: killall maxscale || true
  args:
    warn: false

- name: Wait for 5 Seconds After Killing All MaxScale Service
  wait_for:
    timeout: 5

- name: Reload MaxScale Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk
