---
- name: Wait for 5 Seconds Before Unmounting ZFS Dataset
  wait_for:
    timeout: 5

- name: Unmount ZFS Dataset from Galera Directory
  mount:
    path: /var/lib/mysql
    state: absent

- name: Wait for 5 Seconds After Unmounting ZFS Dataset
  wait_for:
    timeout: 5
