---
- name: Create Galera Databases Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/lib/mysql
    - /var/lib/mysql/bin
    - /var/lib/mysql/data
    - /var/lib/mysql/log
    - /var/lib/mysql/tmp

- name: Create Galera Log Files
  file:
    path: "{{ item }}"
    state: touch
    owner: mysql
    group: mysql
  with_items:
    - /var/lib/mysql/log/mysql.log
    - /var/lib/mysql/log/mysql-err.log
    - /var/lib/mysql/log/mysql-slq.log

- name: Create Galera Run Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/run/mysqld

- name: Create Galera Configurations Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    recurse: true
  with_items:
    - /etc/mysql
    - /etc/mysql/conf.d
