---
- name: Reload Galera Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk

- name: Get Galera Service Info
  shell: service mysql status | grep not-found || true
  args:
    warn: false
  register: galera_service_info
  when:
    - service_init_status.stat.exists

- name: Disable Galera Service
  service:
    name: mysql
    enabled: no
    state: stopped
  when:
    - galera_service_info.stdout.find("not-found") == -1
 
- name: Wait for 5 Seconds Before Killing All Galera Service
  wait_for:
    timeout: 5

- name: Kill All Galera Service
  shell: killall mysqld || true
  args:
    warn: false

- name: Wait for 5 Seconds After Killing All Galera Service
  wait_for:
    timeout: 5

- name: Remove Stale PIDs & Sockets Galera Service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/run/mysqld/mysqld.pid
    - /var/run/mysqld/mysqld.sock
