---
- name: Backing-up Required Galera Configurations
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: true
  with_items:
    - { src: /etc/mysql/debian-start, dest: /tmp/debian-start, mode: '0755' }
    - { src: /etc/mysql/debian.cnf, dest: /tmp/debian.cnf, mode: '0644' }
  when:
    - galera_distribution == 'mariadb-org'

- name: Remove Exsisting Galera Configurations
  shell: rm -rf /etc/mysql/*
  args:
    warn: false

- name: Remove Exsisting Galera Databases Directory
  shell: rm -rf /var/lib/mysql/*
  args:
    warn: false

- name: Find Exsisting Galera Logs
  find:
    paths: /var/log
    patterns: "mysql*"
    use_regex: true
  register: mysql_logs

- name: Remove Exsisting Galera Logs
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items:
    - "{{ mysql_logs['files'] }}"

- name: Find Exsisting Galera Scripts
  find:
    paths: /tmp
    patterns: "mysql*"
    use_regex: true
  register: mysql_scripts

- name: Remove Exsisting Galera Scripts
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items:
    - "{{ mysql_scripts['files'] }}"
