---
- include: facts.yml

- include: apparmor_services.yml

- include: os_packages.yml

- include: zfs_packages.yml
  when:
    - inventory_hostname in groups['galera_node']
    - zfs_backend

- include: zfs_blocks.yml
  when:
    - inventory_hostname in groups['galera_node']
    - zfs_backend

- include: galera_users.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_packages.yml
  when:
    - inventory_hostname in groups['galera_node']
    
- include: galera_services.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_cleanups.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: zfs_mounts.yml
  when:
    - inventory_hostname in groups['galera_node']
    - zfs_backend

- include: galera_directories.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_init_root.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: haproxy_packages.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'haproxy'

- include: haproxy_services.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'haproxy'

- include: haproxy_cleanups.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'haproxy'

- include: maxscale_packages.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'maxscale'

- include: maxscale_services.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'maxscale'

- include: maxscale_cleanups.yml
  when:
    - inventory_hostname in groups['galera_lb']
    - galera_lb_type == 'maxscale'

- include: python_packages.yml

- include: os_cleanups.yml
