---
- name: Wait for 5 Seconds Before Mounting ZFS Dataset
  wait_for:
    timeout: 5

- name: Mount ZFS Dataset to Galera Directory
  mount:
    path: /var/lib/mysql
    src: "/dev/zvol/{{ zfs_pool_name }}/mysql"
    fstype: xfs
    opts: defaults
    passno: 2
    state: mounted

- name: Wait for 5 Seconds After Mounting ZFS Dataset
  wait_for:
    timeout: 5
