---
- name: Generate Galera MySQL Configuration
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate Galera MySQL Client Configuration
  template:
    src: 00_client.cnf.j2
    dest: /etc/mysql/conf.d/00_client.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate Galera MySQL Daemon Configuration
  template:
    src: 00_mysqld.cnf.j2
    dest: /etc/mysql/conf.d/00_mysqld.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate Galera Networks Configuration
  template:
    src: 96_networks.cnf.j2
    dest: /etc/mysql/conf.d/96_networks.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate Galera Storages Configuration
  template:
    src: 97_storages.cnf.j2
    dest: /etc/mysql/conf.d/97_storages.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate Galera Tunnings Configuration
  template:
    src: 98_tunnings.cnf.j2
    dest: /etc/mysql/conf.d/98_tunnings.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate Galera WSREP Configuration
  template:
    src: 99_wsrep.cnf.j2
    dest: /etc/mysql/conf.d/99_wsrep.cnf
    owner: root
    group: root
    mode: 0644

- name: Restoring Required Galera Configurations
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: true
  with_items:
    - { src: /tmp/debian-start, dest: /etc/mysql/debian-start, mode: '0755' }
    - { src: /tmp/debian.cnf, dest: /etc/mysql/debian.cnf, mode: '0644' }
  when:
    - galera_distribution == 'mariadb-org'

- name: Clean-up Backup Required Galera Configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/debian-start
    - /tmp/debian.cnf
  when:
    - galera_distribution == 'mariadb-org'
